### ISSUE TITLE
Invite the PhD Committee

### ISSUE THREAD

**Issue by rtroncy** [ahmadassaf/PhD#7]
## Thesis manuscript:
- If the PhD student wants to write, and present, his/her thesis in English, he/she will need to ask for the Director of the PhD school’s authorization
- If he/she chooses to write the thesis in English, he/she will need to add to the final manuscript a French text of 25 pages to give the main ideas of the thesis, the results, conclusions and the scientific links of the different chapters. This text could be done after the defense.
## Calendar:
- 2 months before the defense:
  - the jury proposition (see doc enclosed, the title of the thesis must be written in FRENCH, and THIS TITLE WILL BE THE OFFICIAL ONE ON ALL THE DEFENSE’S DOCUMENTS)
  - 2 first versions of the thesis (one PDF + another one without the bibliographies' chapter)
    I will send those 3 documents to Télécom ParisTech and they will give me their agreement for the thesis to be defended.
- 8 weeks before the defense: We will have to send the manuscript to the jury members. The reviewers will have 4 weeks to prepare their report and give their agreement for the defense.
- 15 days before the defense: If the reviewers reports are positives, we will send the thesis announcement, using 2 abstracts (1 in French and 1 in English).
- The thesis defense envelope will be given to the advisor the defense's day. When the defense will be finished, the PhD student will have 2 months to prepare his/her administrative ending procedures.
## Jury rules:

Jury proposition: the jury members must be maximum 8 persons. In those 8 persons, you must find the advisor(s), 2 reviewers, and the other jury persons.
- Conditions to be reviewers:
  - they mustn’t be from EDITE or Telecom ParisTech or EURECOM or having links with the PhD student, as co-publications,
  - they must have an HDR or being the same level than a HDR.
- If the advisor is not Professor, we must count a Professor from Télécom ParisTech or EURECOM in the examinators.
- The half of the jury must be Professors.
- The half of the jury must not be from EDITE or telecom ParisTech or EURECOM.
- The jury president must be Professor.
## Tentative Committee
- [x] Prof. Marie Aude Aufaure (Centrale Paris), http://perso.ecp.fr/~aufaurema/ ... **Reviewer 1** ... ... _paper version of the thesis preferred and sent by registered letter_
- [x] Prof. Philippe Cudré-Mauroux (University of Fribourg), http://exascale.info/phil ... **Reviewer 2**  ... _electronic version of the thesis preferred_
- [x] Prof. Pierre Senellart (Telecom ParisTech), http://pierre.senellart.com/ ... **Examiner 1** (since Raphael is not a full prof.) ... _electronic version of the thesis preferred_
- [x] Dr. Stefan Dietze (Leibniz University), https://stefandietze.wordpress.com/ ... **Examiner 2** ... _electronic version of the thesis preferred_
- [x] Dr. Raphaël Troncy (EURECOM), http://www.eurecom.fr/~troncy/ ... **PhD Supervisor**
- [x] Dr. Aline Senart (SAP), https://www.linkedin.com/pub/aline-senart/1/9ba/b35 ... **PhD co-supervisor**
- [x] David Trastour (SAP), https://www.linkedin.com/in/davidtrastour ... **Guest**

**Comment by ahmadassaf** [comment]
Hello @rtroncy, what is the status of this. I am finishing Aline's comments by tomorrow and would be closing #8 and answering Gwenaelle's emails.

**Comment by ahmadassaf** [comment]
I was thinking of alternatives in case some of the suggested people is not able to (and maybe a replacement for Marie :) )
- Prof. Heiko Paulheim (http://dws.informatik.uni-mannheim.de/en/people/professors/dr-heiko-paulheim/)
- Prof. Steffen Staab (http://userpages.uni-koblenz.de/~staab/)
- Prof. Axel Polleres (https://ai.wu.ac.at/~polleres/)
- Prof. Maria-Esther Vidal (http://ldc.usb.ve/~mvidal/)
- Prof. Adrian Paschke (http://www.mi.fu-berlin.de/en/inf/groups/ag-csw/Members/members/Paschke.html)

**Comment by ahmadassaf** [comment]
I have completed the Thesis and we can freeze it now :tada:

**Comment by rtroncy** [comment]
Re-opening, since I have more comments to make. I will take care of closing it in due time

**Comment by ahmadassaf** [comment]
comments on the committee ? does that mean we need to change them as well in the doctoral school form ?

**Comment by rtroncy** [comment]
Read the comments. Preferences on manuscript version. I had to fight with EDITE about the jury but Alain has finally approved the committee today.

**Comment by ahmadassaf** [comment]
am not sure if i am missing something but i don't see any comments anywhere

**Comment by rtroncy** [comment]
The issue is being edited, the new additions are in italics

**Comment by ahmadassaf** [comment]
got it .. i was curious and went on and did a plagiarism check myself on https://www.compilatio.net/.

Is the official one done already ?

<img width="958" alt="screen shot 2015-09-28 at 17 13 23" src="https://cloud.githubusercontent.com/assets/550726/10139783/df44da82-6604-11e5-8ac8-6aa4c99a99d8.png">

**Comment by rtroncy** [comment]
IMT's compilatio account is private

**Comment by rtroncy** [comment]
I have re-done the Compilatio checking and this time indexed publicly your thesis for future plagiarism detection
