### ISSUE TITLE
Declare the PhD committee on the EDITE web site

### ISSUE THREAD

**Issue by rtroncy** [ahmadassaf/PhD#8]
Once issue #7 is resolved (completed), then, @ahmadassaf must declare the committee at https://jurythese.telecom-paristech.fr/sth-fo-auth.

Once this step is done and validated, @rtroncy will run the thesis manuscript on Compilatio (anti-plagiarism tool) and provide the report for enabling the defense.

**Comment by ahmadassaf** [comment]
I have declared all the people and entered them in the system. Upon final confirmation we will remove/confirm people 

<img width="1561" alt="screen shot 2015-09-16 at 17 26 49" src="https://cloud.githubusercontent.com/assets/550726/9909370/33ef5470-5c98-11e5-8e4d-958012a6edca.png">

@rtroncy is there any status on the responses ?

**Comment by rtroncy** [comment]
Let's close this issue only when the jury will have been cleaned and validated by EDITE

**Comment by ahmadassaf** [comment]
cool .. any new updates on that ? to know who confirmed already

**Comment by rtroncy** [comment]
see issue #7, this is made for this
