### ISSUE TITLE
DQV not mentioned in your thesis: major flaw with respect to related work

### ISSUE THREAD

**Issue by rtroncy** [ahmadassaf/PhD#9]
I pointed you before to http://www.w3.org/TR/vocab-dqv/ ... this is not referenced / discussed in your thesis, as far as I can see. I think this should be addressed, also in connexion with the HDL proposed model

**Comment by ahmadassaf** [comment]
Also add: **Open Data Companion (ODC)** " it is an Android app which provides a unified access point to over 100 open data portals and thousands of datasets from around the world; right from your mobile device. Crafted with mobile-optimised features and design, this is an easy and convenient way to find, access and share open data. Open Data Companion provides a framework for all Private Sector, State, Regional, National and  Worldwide CKAN open data portals to deliver open data to all mobile users"

References:
- http://www.socrata.com/open-data-field-guide/open-data-field-kit/
- https://play.google.com/store/apps/details?id=writeosahon.utopiasoftware.odcompanion

**Comment by ahmadassaf** [comment]
References: 
- http://www.w3.org/TR/dwbp/#quality
- http://www.w3.org/TR/vocab-duv/
- http://www.w3.org/TR/vocab-dqv/
